package main

import (
	"syscall"
)

func syscall_name(s uint64) string {
	switch s {
	case syscall.SYS_READ:
		return "SYS_READ"
	case syscall.SYS_WRITE:
		return "SYS_WRITE"
	case syscall.SYS_OPEN:
		return "SYS_OPEN"
	case syscall.SYS_CLOSE:
		return "SYS_CLOSE"
	case syscall.SYS_STAT:
		return "SYS_STAT"
	case syscall.SYS_FSTAT:
		return "SYS_FSTAT"
	case syscall.SYS_LSTAT:
		return "SYS_LSTAT"
	case syscall.SYS_POLL:
		return "SYS_POLL"
	case syscall.SYS_LSEEK:
		return "SYS_LSEEK"
	case syscall.SYS_MMAP:
		return "SYS_MMAP"
	case syscall.SYS_MPROTECT:
		return "SYS_MPROTECT"
	case syscall.SYS_MUNMAP:
		return "SYS_MUNMAP"
	case syscall.SYS_BRK:
		return "SYS_BRK"
	case syscall.SYS_RT_SIGACTION:
		return "SYS_RT_SIGACTION"
	case syscall.SYS_RT_SIGPROCMASK:
		return "SYS_RT_SIGPROCMASK"
	case syscall.SYS_RT_SIGRETURN:
		return "SYS_RT_SIGRETURN"
	case syscall.SYS_IOCTL:
		return "SYS_IOCTL"
	case syscall.SYS_PREAD64:
		return "SYS_PREAD64"
	case syscall.SYS_PWRITE64:
		return "SYS_PWRITE64"
	case syscall.SYS_READV:
		return "SYS_READV"
	case syscall.SYS_WRITEV:
		return "SYS_WRITEV"
	case syscall.SYS_ACCESS:
		return "SYS_ACCESS"
	case syscall.SYS_PIPE:
		return "SYS_PIPE"
	case syscall.SYS_SELECT:
		return "SYS_SELECT"
	case syscall.SYS_SCHED_YIELD:
		return "SYS_SCHED_YIELD"
	case syscall.SYS_MREMAP:
		return "SYS_MREMAP"
	case syscall.SYS_MSYNC:
		return "SYS_MSYNC"
	case syscall.SYS_MINCORE:
		return "SYS_MINCORE"
	case syscall.SYS_MADVISE:
		return "SYS_MADVISE"
	case syscall.SYS_SHMGET:
		return "SYS_SHMGET"
	case syscall.SYS_SHMAT:
		return "SYS_SHMAT"
	case syscall.SYS_SHMCTL:
		return "SYS_SHMCTL"
	case syscall.SYS_DUP:
		return "SYS_DUP"
	case syscall.SYS_DUP2:
		return "SYS_DUP2"
	case syscall.SYS_PAUSE:
		return "SYS_PAUSE"
	case syscall.SYS_NANOSLEEP:
		return "SYS_NANOSLEEP"
	case syscall.SYS_GETITIMER:
		return "SYS_GETITIMER"
	case syscall.SYS_ALARM:
		return "SYS_ALARM"
	case syscall.SYS_SETITIMER:
		return "SYS_SETITIMER"
	case syscall.SYS_GETPID:
		return "SYS_GETPID"
	case syscall.SYS_SENDFILE:
		return "SYS_SENDFILE"
	case syscall.SYS_SOCKET:
		return "SYS_SOCKET"
	case syscall.SYS_CONNECT:
		return "SYS_CONNECT"
	case syscall.SYS_ACCEPT:
		return "SYS_ACCEPT"
	case syscall.SYS_SENDTO:
		return "SYS_SENDTO"
	case syscall.SYS_RECVFROM:
		return "SYS_RECVFROM"
	case syscall.SYS_SENDMSG:
		return "SYS_SENDMSG"
	case syscall.SYS_RECVMSG:
		return "SYS_RECVMSG"
	case syscall.SYS_SHUTDOWN:
		return "SYS_SHUTDOWN"
	case syscall.SYS_BIND:
		return "SYS_BIND"
	case syscall.SYS_LISTEN:
		return "SYS_LISTEN"
	case syscall.SYS_GETSOCKNAME:
		return "SYS_GETSOCKNAME"
	case syscall.SYS_GETPEERNAME:
		return "SYS_GETPEERNAME"
	case syscall.SYS_SOCKETPAIR:
		return "SYS_SOCKETPAIR"
	case syscall.SYS_SETSOCKOPT:
		return "SYS_SETSOCKOPT"
	case syscall.SYS_GETSOCKOPT:
		return "SYS_GETSOCKOPT"
	case syscall.SYS_CLONE:
		return "SYS_CLONE"
	case syscall.SYS_FORK:
		return "SYS_FORK"
	case syscall.SYS_VFORK:
		return "SYS_VFORK"
	case syscall.SYS_EXECVE:
		return "SYS_EXECVE"
	case syscall.SYS_EXIT:
		return "SYS_EXIT"
	case syscall.SYS_WAIT4:
		return "SYS_WAIT4"
	case syscall.SYS_KILL:
		return "SYS_KILL"
	case syscall.SYS_UNAME:
		return "SYS_UNAME"
	case syscall.SYS_SEMGET:
		return "SYS_SEMGET"
	case syscall.SYS_SEMOP:
		return "SYS_SEMOP"
	case syscall.SYS_SEMCTL:
		return "SYS_SEMCTL"
	case syscall.SYS_SHMDT:
		return "SYS_SHMDT"
	case syscall.SYS_MSGGET:
		return "SYS_MSGGET"
	case syscall.SYS_MSGSND:
		return "SYS_MSGSND"
	case syscall.SYS_MSGRCV:
		return "SYS_MSGRCV"
	case syscall.SYS_MSGCTL:
		return "SYS_MSGCTL"
	case syscall.SYS_FCNTL:
		return "SYS_FCNTL"
	case syscall.SYS_FLOCK:
		return "SYS_FLOCK"
	case syscall.SYS_FSYNC:
		return "SYS_FSYNC"
	case syscall.SYS_FDATASYNC:
		return "SYS_FDATASYNC"
	case syscall.SYS_TRUNCATE:
		return "SYS_TRUNCATE"
	case syscall.SYS_FTRUNCATE:
		return "SYS_FTRUNCATE"
	case syscall.SYS_GETDENTS:
		return "SYS_GETDENTS"
	case syscall.SYS_GETCWD:
		return "SYS_GETCWD"
	case syscall.SYS_CHDIR:
		return "SYS_CHDIR"
	case syscall.SYS_FCHDIR:
		return "SYS_FCHDIR"
	case syscall.SYS_RENAME:
		return "SYS_RENAME"
	case syscall.SYS_MKDIR:
		return "SYS_MKDIR"
	case syscall.SYS_RMDIR:
		return "SYS_RMDIR"
	case syscall.SYS_CREAT:
		return "SYS_CREAT"
	case syscall.SYS_LINK:
		return "SYS_LINK"
	case syscall.SYS_UNLINK:
		return "SYS_UNLINK"
	case syscall.SYS_SYMLINK:
		return "SYS_SYMLINK"
	case syscall.SYS_READLINK:
		return "SYS_READLINK"
	case syscall.SYS_CHMOD:
		return "SYS_CHMOD"
	case syscall.SYS_FCHMOD:
		return "SYS_FCHMOD"
	case syscall.SYS_CHOWN:
		return "SYS_CHOWN"
	case syscall.SYS_FCHOWN:
		return "SYS_FCHOWN"
	case syscall.SYS_LCHOWN:
		return "SYS_LCHOWN"
	case syscall.SYS_UMASK:
		return "SYS_UMASK"
	case syscall.SYS_GETTIMEOFDAY:
		return "SYS_GETTIMEOFDAY"
	case syscall.SYS_GETRLIMIT:
		return "SYS_GETRLIMIT"
	case syscall.SYS_GETRUSAGE:
		return "SYS_GETRUSAGE"
	case syscall.SYS_SYSINFO:
		return "SYS_SYSINFO"
	case syscall.SYS_TIMES:
		return "SYS_TIMES"
	case syscall.SYS_PTRACE:
		return "SYS_PTRACE"
	case syscall.SYS_GETUID:
		return "SYS_GETUID"
	case syscall.SYS_SYSLOG:
		return "SYS_SYSLOG"
	case syscall.SYS_GETGID:
		return "SYS_GETGID"
	case syscall.SYS_SETUID:
		return "SYS_SETUID"
	case syscall.SYS_SETGID:
		return "SYS_SETGID"
	case syscall.SYS_GETEUID:
		return "SYS_GETEUID"
	case syscall.SYS_GETEGID:
		return "SYS_GETEGID"
	case syscall.SYS_SETPGID:
		return "SYS_SETPGID"
	case syscall.SYS_GETPPID:
		return "SYS_GETPPID"
	case syscall.SYS_GETPGRP:
		return "SYS_GETPGRP"
	case syscall.SYS_SETSID:
		return "SYS_SETSID"
	case syscall.SYS_SETREUID:
		return "SYS_SETREUID"
	case syscall.SYS_SETREGID:
		return "SYS_SETREGID"
	case syscall.SYS_GETGROUPS:
		return "SYS_GETGROUPS"
	case syscall.SYS_SETGROUPS:
		return "SYS_SETGROUPS"
	case syscall.SYS_SETRESUID:
		return "SYS_SETRESUID"
	case syscall.SYS_GETRESUID:
		return "SYS_GETRESUID"
	case syscall.SYS_SETRESGID:
		return "SYS_SETRESGID"
	case syscall.SYS_GETRESGID:
		return "SYS_GETRESGID"
	case syscall.SYS_GETPGID:
		return "SYS_GETPGID"
	case syscall.SYS_SETFSUID:
		return "SYS_SETFSUID"
	case syscall.SYS_SETFSGID:
		return "SYS_SETFSGID"
	case syscall.SYS_GETSID:
		return "SYS_GETSID"
	case syscall.SYS_CAPGET:
		return "SYS_CAPGET"
	case syscall.SYS_CAPSET:
		return "SYS_CAPSET"
	case syscall.SYS_RT_SIGPENDING:
		return "SYS_RT_SIGPENDING"
	case syscall.SYS_RT_SIGTIMEDWAIT:
		return "SYS_RT_SIGTIMEDWAIT"
	case syscall.SYS_RT_SIGQUEUEINFO:
		return "SYS_RT_SIGQUEUEINFO"
	case syscall.SYS_RT_SIGSUSPEND:
		return "SYS_RT_SIGSUSPEND"
	case syscall.SYS_SIGALTSTACK:
		return "SYS_SIGALTSTACK"
	case syscall.SYS_UTIME:
		return "SYS_UTIME"
	case syscall.SYS_MKNOD:
		return "SYS_MKNOD"
	case syscall.SYS_USELIB:
		return "SYS_USELIB"
	case syscall.SYS_PERSONALITY:
		return "SYS_PERSONALITY"
	case syscall.SYS_USTAT:
		return "SYS_USTAT"
	case syscall.SYS_STATFS:
		return "SYS_STATFS"
	case syscall.SYS_FSTATFS:
		return "SYS_FSTATFS"
	case syscall.SYS_SYSFS:
		return "SYS_SYSFS"
	case syscall.SYS_GETPRIORITY:
		return "SYS_GETPRIORITY"
	case syscall.SYS_SETPRIORITY:
		return "SYS_SETPRIORITY"
	case syscall.SYS_SCHED_SETPARAM:
		return "SYS_SCHED_SETPARAM"
	case syscall.SYS_SCHED_GETPARAM:
		return "SYS_SCHED_GETPARAM"
	case syscall.SYS_SCHED_SETSCHEDULER:
		return "SYS_SCHED_SETSCHEDULER"
	case syscall.SYS_SCHED_GETSCHEDULER:
		return "SYS_SCHED_GETSCHEDULER"
	case syscall.SYS_SCHED_GET_PRIORITY_MAX:
		return "SYS_SCHED_GET_PRIORITY_MAX"
	case syscall.SYS_SCHED_GET_PRIORITY_MIN:
		return "SYS_SCHED_GET_PRIORITY_MIN"
	case syscall.SYS_SCHED_RR_GET_INTERVAL:
		return "SYS_SCHED_RR_GET_INTERVAL"
	case syscall.SYS_MLOCK:
		return "SYS_MLOCK"
	case syscall.SYS_MUNLOCK:
		return "SYS_MUNLOCK"
	case syscall.SYS_MLOCKALL:
		return "SYS_MLOCKALL"
	case syscall.SYS_MUNLOCKALL:
		return "SYS_MUNLOCKALL"
	case syscall.SYS_VHANGUP:
		return "SYS_VHANGUP"
	case syscall.SYS_MODIFY_LDT:
		return "SYS_MODIFY_LDT"
	case syscall.SYS_PIVOT_ROOT:
		return "SYS_PIVOT_ROOT"
	case syscall.SYS__SYSCTL:
		return "SYS__SYSCTL"
	case syscall.SYS_PRCTL:
		return "SYS_PRCTL"
	case syscall.SYS_ARCH_PRCTL:
		return "SYS_ARCH_PRCTL"
	case syscall.SYS_ADJTIMEX:
		return "SYS_ADJTIMEX"
	case syscall.SYS_SETRLIMIT:
		return "SYS_SETRLIMIT"
	case syscall.SYS_CHROOT:
		return "SYS_CHROOT"
	case syscall.SYS_SYNC:
		return "SYS_SYNC"
	case syscall.SYS_ACCT:
		return "SYS_ACCT"
	case syscall.SYS_SETTIMEOFDAY:
		return "SYS_SETTIMEOFDAY"
	case syscall.SYS_MOUNT:
		return "SYS_MOUNT"
	case syscall.SYS_UMOUNT2:
		return "SYS_UMOUNT2"
	case syscall.SYS_SWAPON:
		return "SYS_SWAPON"
	case syscall.SYS_SWAPOFF:
		return "SYS_SWAPOFF"
	case syscall.SYS_REBOOT:
		return "SYS_REBOOT"
	case syscall.SYS_SETHOSTNAME:
		return "SYS_SETHOSTNAME"
	case syscall.SYS_SETDOMAINNAME:
		return "SYS_SETDOMAINNAME"
	case syscall.SYS_IOPL:
		return "SYS_IOPL"
	case syscall.SYS_IOPERM:
		return "SYS_IOPERM"
	case syscall.SYS_CREATE_MODULE:
		return "SYS_CREATE_MODULE"
	case syscall.SYS_INIT_MODULE:
		return "SYS_INIT_MODULE"
	case syscall.SYS_DELETE_MODULE:
		return "SYS_DELETE_MODULE"
	case syscall.SYS_GET_KERNEL_SYMS:
		return "SYS_GET_KERNEL_SYMS"
	case syscall.SYS_QUERY_MODULE:
		return "SYS_QUERY_MODULE"
	case syscall.SYS_QUOTACTL:
		return "SYS_QUOTACTL"
	case syscall.SYS_NFSSERVCTL:
		return "SYS_NFSSERVCTL"
	case syscall.SYS_GETPMSG:
		return "SYS_GETPMSG"
	case syscall.SYS_PUTPMSG:
		return "SYS_PUTPMSG"
	case syscall.SYS_AFS_SYSCALL:
		return "SYS_AFS_SYSCALL"
	case syscall.SYS_TUXCALL:
		return "SYS_TUXCALL"
	case syscall.SYS_SECURITY:
		return "SYS_SECURITY"
	case syscall.SYS_GETTID:
		return "SYS_GETTID"
	case syscall.SYS_READAHEAD:
		return "SYS_READAHEAD"
	case syscall.SYS_SETXATTR:
		return "SYS_SETXATTR"
	case syscall.SYS_LSETXATTR:
		return "SYS_LSETXATTR"
	case syscall.SYS_FSETXATTR:
		return "SYS_FSETXATTR"
	case syscall.SYS_GETXATTR:
		return "SYS_GETXATTR"
	case syscall.SYS_LGETXATTR:
		return "SYS_LGETXATTR"
	case syscall.SYS_FGETXATTR:
		return "SYS_FGETXATTR"
	case syscall.SYS_LISTXATTR:
		return "SYS_LISTXATTR"
	case syscall.SYS_LLISTXATTR:
		return "SYS_LLISTXATTR"
	case syscall.SYS_FLISTXATTR:
		return "SYS_FLISTXATTR"
	case syscall.SYS_REMOVEXATTR:
		return "SYS_REMOVEXATTR"
	case syscall.SYS_LREMOVEXATTR:
		return "SYS_LREMOVEXATTR"
	case syscall.SYS_FREMOVEXATTR:
		return "SYS_FREMOVEXATTR"
	case syscall.SYS_TKILL:
		return "SYS_TKILL"
	case syscall.SYS_TIME:
		return "SYS_TIME"
	case syscall.SYS_FUTEX:
		return "SYS_FUTEX"
	case syscall.SYS_SCHED_SETAFFINITY:
		return "SYS_SCHED_SETAFFINITY"
	case syscall.SYS_SCHED_GETAFFINITY:
		return "SYS_SCHED_GETAFFINITY"
	case syscall.SYS_SET_THREAD_AREA:
		return "SYS_SET_THREAD_AREA"
	case syscall.SYS_IO_SETUP:
		return "SYS_IO_SETUP"
	case syscall.SYS_IO_DESTROY:
		return "SYS_IO_DESTROY"
	case syscall.SYS_IO_GETEVENTS:
		return "SYS_IO_GETEVENTS"
	case syscall.SYS_IO_SUBMIT:
		return "SYS_IO_SUBMIT"
	case syscall.SYS_IO_CANCEL:
		return "SYS_IO_CANCEL"
	case syscall.SYS_GET_THREAD_AREA:
		return "SYS_GET_THREAD_AREA"
	case syscall.SYS_LOOKUP_DCOOKIE:
		return "SYS_LOOKUP_DCOOKIE"
	case syscall.SYS_EPOLL_CREATE:
		return "SYS_EPOLL_CREATE"
	case syscall.SYS_EPOLL_CTL_OLD:
		return "SYS_EPOLL_CTL_OLD"
	case syscall.SYS_EPOLL_WAIT_OLD:
		return "SYS_EPOLL_WAIT_OLD"
	case syscall.SYS_REMAP_FILE_PAGES:
		return "SYS_REMAP_FILE_PAGES"
	case syscall.SYS_GETDENTS64:
		return "SYS_GETDENTS64"
	case syscall.SYS_SET_TID_ADDRESS:
		return "SYS_SET_TID_ADDRESS"
	case syscall.SYS_RESTART_SYSCALL:
		return "SYS_RESTART_SYSCALL"
	case syscall.SYS_SEMTIMEDOP:
		return "SYS_SEMTIMEDOP"
	case syscall.SYS_FADVISE64:
		return "SYS_FADVISE64"
	case syscall.SYS_TIMER_CREATE:
		return "SYS_TIMER_CREATE"
	case syscall.SYS_TIMER_SETTIME:
		return "SYS_TIMER_SETTIME"
	case syscall.SYS_TIMER_GETTIME:
		return "SYS_TIMER_GETTIME"
	case syscall.SYS_TIMER_GETOVERRUN:
		return "SYS_TIMER_GETOVERRUN"
	case syscall.SYS_TIMER_DELETE:
		return "SYS_TIMER_DELETE"
	case syscall.SYS_CLOCK_SETTIME:
		return "SYS_CLOCK_SETTIME"
	case syscall.SYS_CLOCK_GETTIME:
		return "SYS_CLOCK_GETTIME"
	case syscall.SYS_CLOCK_GETRES:
		return "SYS_CLOCK_GETRES"
	case syscall.SYS_CLOCK_NANOSLEEP:
		return "SYS_CLOCK_NANOSLEEP"
	case syscall.SYS_EXIT_GROUP:
		return "SYS_EXIT_GROUP"
	case syscall.SYS_EPOLL_WAIT:
		return "SYS_EPOLL_WAIT"
	case syscall.SYS_EPOLL_CTL:
		return "SYS_EPOLL_CTL"
	case syscall.SYS_TGKILL:
		return "SYS_TGKILL"
	case syscall.SYS_UTIMES:
		return "SYS_UTIMES"
	case syscall.SYS_VSERVER:
		return "SYS_VSERVER"
	case syscall.SYS_MBIND:
		return "SYS_MBIND"
	case syscall.SYS_SET_MEMPOLICY:
		return "SYS_SET_MEMPOLICY"
	case syscall.SYS_GET_MEMPOLICY:
		return "SYS_GET_MEMPOLICY"
	case syscall.SYS_MQ_OPEN:
		return "SYS_MQ_OPEN"
	case syscall.SYS_MQ_UNLINK:
		return "SYS_MQ_UNLINK"
	case syscall.SYS_MQ_TIMEDSEND:
		return "SYS_MQ_TIMEDSEND"
	case syscall.SYS_MQ_TIMEDRECEIVE:
		return "SYS_MQ_TIMEDRECEIVE"
	case syscall.SYS_MQ_NOTIFY:
		return "SYS_MQ_NOTIFY"
	case syscall.SYS_MQ_GETSETATTR:
		return "SYS_MQ_GETSETATTR"
	case syscall.SYS_KEXEC_LOAD:
		return "SYS_KEXEC_LOAD"
	case syscall.SYS_WAITID:
		return "SYS_WAITID"
	case syscall.SYS_ADD_KEY:
		return "SYS_ADD_KEY"
	case syscall.SYS_REQUEST_KEY:
		return "SYS_REQUEST_KEY"
	case syscall.SYS_KEYCTL:
		return "SYS_KEYCTL"
	case syscall.SYS_IOPRIO_SET:
		return "SYS_IOPRIO_SET"
	case syscall.SYS_IOPRIO_GET:
		return "SYS_IOPRIO_GET"
	case syscall.SYS_INOTIFY_INIT:
		return "SYS_INOTIFY_INIT"
	case syscall.SYS_INOTIFY_ADD_WATCH:
		return "SYS_INOTIFY_ADD_WATCH"
	case syscall.SYS_INOTIFY_RM_WATCH:
		return "SYS_INOTIFY_RM_WATCH"
	case syscall.SYS_MIGRATE_PAGES:
		return "SYS_MIGRATE_PAGES"
	case syscall.SYS_OPENAT:
		return "SYS_OPENAT"
	case syscall.SYS_MKDIRAT:
		return "SYS_MKDIRAT"
	case syscall.SYS_MKNODAT:
		return "SYS_MKNODAT"
	case syscall.SYS_FCHOWNAT:
		return "SYS_FCHOWNAT"
	case syscall.SYS_FUTIMESAT:
		return "SYS_FUTIMESAT"
	case syscall.SYS_NEWFSTATAT:
		return "SYS_NEWFSTATAT"
	case syscall.SYS_UNLINKAT:
		return "SYS_UNLINKAT"
	case syscall.SYS_RENAMEAT:
		return "SYS_RENAMEAT"
	case syscall.SYS_LINKAT:
		return "SYS_LINKAT"
	case syscall.SYS_SYMLINKAT:
		return "SYS_SYMLINKAT"
	case syscall.SYS_READLINKAT:
		return "SYS_READLINKAT"
	case syscall.SYS_FCHMODAT:
		return "SYS_FCHMODAT"
	case syscall.SYS_FACCESSAT:
		return "SYS_FACCESSAT"
	case syscall.SYS_PSELECT6:
		return "SYS_PSELECT6"
	case syscall.SYS_PPOLL:
		return "SYS_PPOLL"
	case syscall.SYS_UNSHARE:
		return "SYS_UNSHARE"
	case syscall.SYS_SET_ROBUST_LIST:
		return "SYS_SET_ROBUST_LIST"
	case syscall.SYS_GET_ROBUST_LIST:
		return "SYS_GET_ROBUST_LIST"
	case syscall.SYS_SPLICE:
		return "SYS_SPLICE"
	case syscall.SYS_TEE:
		return "SYS_TEE"
	case syscall.SYS_SYNC_FILE_RANGE:
		return "SYS_SYNC_FILE_RANGE"
	case syscall.SYS_VMSPLICE:
		return "SYS_VMSPLICE"
	case syscall.SYS_MOVE_PAGES:
		return "SYS_MOVE_PAGES"
	case syscall.SYS_UTIMENSAT:
		return "SYS_UTIMENSAT"
	case syscall.SYS_EPOLL_PWAIT:
		return "SYS_EPOLL_PWAIT"
	case syscall.SYS_SIGNALFD:
		return "SYS_SIGNALFD"
	case syscall.SYS_TIMERFD_CREATE:
		return "SYS_TIMERFD_CREATE"
	case syscall.SYS_EVENTFD:
		return "SYS_EVENTFD"
	case syscall.SYS_FALLOCATE:
		return "SYS_FALLOCATE"
	case syscall.SYS_TIMERFD_SETTIME:
		return "SYS_TIMERFD_SETTIME"
	case syscall.SYS_TIMERFD_GETTIME:
		return "SYS_TIMERFD_GETTIME"
	case syscall.SYS_ACCEPT4:
		return "SYS_ACCEPT4"
	case syscall.SYS_SIGNALFD4:
		return "SYS_SIGNALFD4"
	case syscall.SYS_EVENTFD2:
		return "SYS_EVENTFD2"
	case syscall.SYS_EPOLL_CREATE1:
		return "SYS_EPOLL_CREATE1"
	case syscall.SYS_DUP3:
		return "SYS_DUP3"
	case syscall.SYS_PIPE2:
		return "SYS_PIPE2"
	case syscall.SYS_INOTIFY_INIT1:
		return "SYS_INOTIFY_INIT1"
	case syscall.SYS_PREADV:
		return "SYS_PREADV"
	case syscall.SYS_PWRITEV:
		return "SYS_PWRITEV"
	case syscall.SYS_RT_TGSIGQUEUEINFO:
		return "SYS_RT_TGSIGQUEUEINFO"
	case syscall.SYS_PERF_EVENT_OPEN:
		return "SYS_PERF_EVENT_OPEN"
	case syscall.SYS_RECVMMSG:
		return "SYS_RECVMMSG"
	case syscall.SYS_FANOTIFY_INIT:
		return "SYS_FANOTIFY_INIT"
	case syscall.SYS_FANOTIFY_MARK:
		return "SYS_FANOTIFY_MARK"
	case syscall.SYS_PRLIMIT64:
		return "SYS_PRLIMIT64"
	default:
	}
	return "SYS_UNKNOWN"
}
